"""add face_encoding to user

Revision ID: cdc6917a7734
Revises: 7c6deeefdfa7
Create Date: 2025-01-04 17:47:44.759041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc6917a7734'
down_revision: Union[str, None] = '7c6deeefdfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_encoding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_encoding')
    # ### end Alembic commands ###
